name: onyx_lighting
description: A library to interface with the Onyx Lighting controller by Obsidian
version: 0.0.3
homepage: http://jeffmikels.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
