name: onyx_lighting
description: A library to interface with the Onyx Lighting controller by Obsidian
version: 0.0.5
homepage: http://jeffmikels.com/
repository: https://github.com/jeffmikels/onyx_lighting_dart


environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
